relativeURLs = true
title = "Canishk Naik"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]
baseURL = "https://canishknaik.github.io/"

[params]
    shortbio = "PhD candidate in Economics, LSE"
    logo = "cn_headshot.jpg"
